version: '3.8'

services:
  dbsql:
    container_name: dbsql
    image: postgres:16.1-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbsql_volume:/var/lib/postgresql/data/
      - ./db/dbsql_volume:/var/lib/postgresql/data/
    networks:
      - docker_network
    restart: unless-stopped

volumes:
  dbsql_volume:
networks:
  docker_network:
